name: Push Files on Tag

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0, v2.1.0, etc.

jobs:
  push_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetched so we can access tags

      - name: Set up Git
        # git config user.email "${{ github.actor }}@users.noreply.github.com"
        run: |
          git config user.name "${{ github.actor }}"

      - name: Select files to push
        run: |
          cp -r pygchat selected_files/
          cp README.md selected_files/

      - name: Commit selected files
        run: |
          cd selected_files
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git checkout -b Releases
          git add .
          git commit -m "Add selected files on tag ${{ github.ref_name }}"

      - name: Push to target branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd selected_files
          git push origin Releases --force